/**
 * Auto-generated atlas asset registry.
 * Maps atlas filename → require() asset for Metro bundler.
 * Regenerated by the consuming app's atlas build script (in Facet:
 * `npm run build:atlases`); no script exists in this repo.
 */

/* eslint-disable @typescript-eslint/no-require-imports */

export const ATLAS_ASSETS: Record<string, number> = {
  'all_L0.png': require('../assets/images/atlases/all_L0.png'),
  'all_L1.png': require('../assets/images/atlases/all_L1.png'),
  'angular_L2.png': require('../assets/images/atlases/angular_L2.png'),
  'angular_L3.png': require('../assets/images/atlases/angular_L3.png'),
  'angular_L4.png': require('../assets/images/atlases/angular_L4.png'),
  'cloud_L2.png': require('../assets/images/atlases/cloud_L2.png'),
  'cloud_L3.png': require('../assets/images/atlases/cloud_L3.png'),
  'cloud_L4.png': require('../assets/images/atlases/cloud_L4.png'),
  'craftsman_L2.png': require('../assets/images/atlases/craftsman_L2.png'),
  'craftsman_L3.png': require('../assets/images/atlases/craftsman_L3.png'),
  'craftsman_L4.png': require('../assets/images/atlases/craftsman_L4.png'),
  'curved_L2.png': require('../assets/images/atlases/curved_L2.png'),
  'curved_L3.png': require('../assets/images/atlases/curved_L3.png'),
  'curved_L4.png': require('../assets/images/atlases/curved_L4.png'),
  'petal_L2.png': require('../assets/images/atlases/petal_L2.png'),
  'petal_L3.png': require('../assets/images/atlases/petal_L3.png'),
  'petal_L4.png': require('../assets/images/atlases/petal_L4.png'),
};
