import {
  Layer,
  EditorState,
  GridLevel,
  LAYER_PX,
  initDirtyRects,
  makeViewport,
} from '../types';
import { createCellGrid } from '../cells';

export function makeLayer(id: string, level: GridLevel = 0, order: number = 0): Layer {
  const data = new Uint8Array(LAYER_PX * LAYER_PX * 4);
  return {
    id,
    name: `Layer ${id}`,
    level,
    visible: true,
    opacity: 1,
    order,
    shiftX: 0,
    shiftY: 0,
    locked: false,
    data,
    dataU32: new Uint32Array(data.buffer),
    dirtyRects: initDirtyRects(),
    dirtyRectCount: 0,
    cells: createCellGrid(level),
    cellsGeneration: 0,
    edgeRowTop: null,
    edgeColLeft: null,
    edgeCorner: null,
  };
}

export function makeState(layers?: Layer[], overrides?: Partial<EditorState>): EditorState {
  const ls = layers ?? [makeLayer('test', 0, 0)];
  return {
    fileConfig: { id: 'test-file', name: 'Test' },
    layers: ls,
    activeLayerId: ls[0].id,
    tool: { type: 'color', colorIndex: 0 },
    drawTool: { type: 'color', colorIndex: 0 },
    camera: { offsetX: 0, offsetY: 0, zoom: 1 },
    viewport: makeViewport(800, 600),
    renderGeneration: 0,
    atlasGeneration: 0,
    lastCellEdits: [],
    mirrorH: false,
    mirrorV: false,
    mirrorRotate: false,
    mirrorQuad: false,
    mirrorRow: false,
    mirrorCol: false,
    mirrorDiag1: false,
    mirrorDiag2: false,
    mirrorDiagBoth: false,
    mirrorStar: false,
    selection: null,
    selectionSubTool: 'move',
    movePreview: null,
    rotatePreview: null,
    deepEdit: true,
    copySelection: false,
    autoHighlight: false,
    patterns: [],
    activePatternId: null,
    activePatternRotation: 0,
    patternOrigin: null,
    allowBorderConnections: true,
    multiresFill: false,
    excludedFamilies: new Set(),
    cloneSourceIndex: null,
    cloneSampleIndex: null,
    cloneAnchorIndex: null,
    cloneCursorIndex: null,
    selectionMode: 'rect',
    pathIndices: new Set(),
    pathLevel: 0,
    pathGeneration: 0,
    pathL0Indices: null,
    resizingCanvas: false,
    activeColorR: 255,
    activeColorG: 255,
    activeColorB: 255,
    ...overrides,
  };
}
