/**
 * Schema for the dynamic-samples manifest. The manifest is generated by
 * the app repo's build-dynamic-manifest script at build time and deployed
 * alongside the web bundle. The client fetches it on every cold start
 * with an ETag.
 *
 * Paths inside an entry are origin-relative (`/dynamic-samples/...`) so the
 * same manifest works for web (same-origin) and mobile (prefixed with the
 * configured base URL).
 */

/** Bumped only on breaking shape changes. Older clients reject manifests
 *  whose `schemaVersion` is not exactly this value, preserving their
 *  last-known-good cached entries. */
export const MANIFEST_SCHEMA_VERSION = 1 as const;

/** Hard cap on `.tile` payload size — verified against `compSize` from the
 *  manifest before fetch and against the actual downloaded length after. */
export const MAX_SAMPLE_BYTES = 10 * 1024 * 1024;

export interface DynamicSampleManifestEntry {
  /** Stable id (UUID), persisted into the source-side meta sidecar so
   *  re-runs of the build script don't churn ids. */
  id: string;
  /** Filename-safe internal name. Becomes the imported composition's `name`
   *  unless `displayName` is also set. */
  name: string;
  displayName?: string;
  tags?: string[];
  /** ms-since-epoch. Sort key for newest-first ordering within a tag group. */
  createdAt: number;
  /** ms-since-epoch. Client hides entries whose publishDate is in the future.
   *  Entries without an explicit publishDate from the CMS (or without an
   *  `.activity` sidecar) are kept here as `Number.POSITIVE_INFINITY` so
   *  the `publishDate <= now` filter naturally hides them until the CMS
   *  publishes them. */
  publishDate: number;
  /** Origin-relative path to the .tile blob, e.g. `/dynamic-samples/blob/<sha>.tile`. */
  compPath: string;
  compSize: number;
  /** Hex-encoded sha256 of the blob, verified after download. */
  compSha256: string;
  /** Origin-relative path to the thumbnail (WebP/PNG). */
  thumbPath: string;
  /** Optional .activity sidecar path. */
  activityPath?: string;
  /** Optional inline banner — overridden by activity sidecar if both present. */
  bannerText?: string;
  /** Origin-relative paths to example images, e.g. `/dynamic-samples/examples/Beads_example_01.png`. */
  exampleImagePaths?: string[];
}

export interface DynamicSampleManifest {
  schemaVersion: typeof MANIFEST_SCHEMA_VERSION;
  /** Cosmetic timestamp; ETag drives caching. */
  generatedAt: number;
  samples: DynamicSampleManifestEntry[];
}

const HEX_SHA256_RE = /^[0-9a-f]{64}$/;
const ALLOWED_PATH_PREFIX = '/dynamic-samples/';

function isFiniteNumber(v: unknown): v is number {
  return typeof v === 'number' && Number.isFinite(v);
}

function isOriginRelativeUnderDynamicSamples(v: unknown): v is string {
  if (typeof v !== 'string') return false;
  if (!v.startsWith(ALLOWED_PATH_PREFIX)) return false;
  // Disallow scheme/authority confusion. A leading `/` followed by another
  // `/` could trick a URL parser into treating the rest as a host.
  if (v.startsWith('//')) return false;
  if (v.includes('..')) return false;
  return true;
}

function parseEntry(raw: unknown): DynamicSampleManifestEntry | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;

  if (typeof r.id !== 'string' || r.id.length === 0) return null;
  if (typeof r.name !== 'string' || r.name.length === 0) return null;
  if (!isFiniteNumber(r.createdAt)) return null;
  if (!isOriginRelativeUnderDynamicSamples(r.compPath)) return null;
  if (!isFiniteNumber(r.compSize) || r.compSize <= 0 || r.compSize > MAX_SAMPLE_BYTES) return null;
  if (typeof r.compSha256 !== 'string' || !HEX_SHA256_RE.test(r.compSha256)) return null;
  if (!isOriginRelativeUnderDynamicSamples(r.thumbPath)) return null;

  // Missing publishDate means the CMS hasn't scheduled this entry yet —
  // surface it as POSITIVE_INFINITY so the runtime `publishDate <= now`
  // filter hides it. Same treatment when the entry has no `.activity`
  // sidecar (applied below once activityPath is parsed).
  const publishDate = isFiniteNumber(r.publishDate) ? r.publishDate : Number.POSITIVE_INFINITY;

  const entry: DynamicSampleManifestEntry = {
    id: r.id,
    name: r.name,
    createdAt: r.createdAt,
    publishDate,
    compPath: r.compPath,
    compSize: r.compSize,
    compSha256: r.compSha256,
    thumbPath: r.thumbPath,
  };

  if (typeof r.displayName === 'string' && r.displayName.length > 0) {
    entry.displayName = r.displayName;
  }
  if (Array.isArray(r.tags)) {
    const validTags = r.tags.filter((t: unknown): t is string => typeof t === 'string' && t.length > 0);
    if (validTags.length > 0) entry.tags = validTags;
  }
  if (typeof r.activityPath === 'string') {
    if (!isOriginRelativeUnderDynamicSamples(r.activityPath)) return null;
    entry.activityPath = r.activityPath;
  } else {
    // No sidecar → not available regardless of any publishDate the CMS may
    // have emitted. Defense-in-depth against a CMS regression that lets a
    // publishDate ship without an activity file.
    entry.publishDate = Number.POSITIVE_INFINITY;
  }
  if (typeof r.bannerText === 'string' && r.bannerText.length > 0) {
    entry.bannerText = r.bannerText;
  }
  if (Array.isArray(r.exampleImagePaths)) {
    const valid = r.exampleImagePaths.filter(
      (p: unknown): p is string => isOriginRelativeUnderDynamicSamples(p),
    );
    if (valid.length > 0) entry.exampleImagePaths = valid;
  }
  return entry;
}

/**
 * Validate a parsed manifest payload. Returns null on any structural
 * problem — callers fall back to the cached manifest rather than throwing.
 *
 * Accepts either a raw object (already JSON-parsed) or a JSON string.
 */
export function parseManifest(raw: unknown): DynamicSampleManifest | null {
  let obj: unknown = raw;
  if (typeof raw === 'string') {
    try {
      obj = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  if (!obj || typeof obj !== 'object') return null;
  const r = obj as Record<string, unknown>;
  if (r.schemaVersion !== MANIFEST_SCHEMA_VERSION) return null;
  if (!isFiniteNumber(r.generatedAt)) return null;
  if (!Array.isArray(r.samples)) return null;

  const samples: DynamicSampleManifestEntry[] = [];
  const seenIds = new Set<string>();
  for (const item of r.samples) {
    const entry = parseEntry(item);
    if (!entry) return null;
    if (seenIds.has(entry.id)) return null;
    seenIds.add(entry.id);
    samples.push(entry);
  }
  return {
    schemaVersion: MANIFEST_SCHEMA_VERSION,
    generatedAt: r.generatedAt,
    samples,
  };
}
